from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from train_pace_loss import add_features, make_ridge, ridge_design


# ============================================================
# PATHS / SETTINGS
# ============================================================

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"

LAPS_FILE = DATA_DIR / "laps_clean.csv"
STINTS_FILE = DATA_DIR / "stints.csv"

RAW_OUTPUT = DATA_DIR / "tyre_radar_raw.csv"
RADAR_OUTPUT = DATA_DIR / "tyre_radar_scores.csv"
RADAR_PNG = DATA_DIR / "tyre_radar.png"

COMPOUNDS = [
    "HARD",
    "MEDIUM",
    "SOFT",
    "INTERMEDIATE",
]

# Radar index settings.
#
# 50 = reference mean
# 20 = one standard deviation from the mean
#
# These are relative scores, NOT percentages.
BASE_SCORE = 50.0
SCALE = 20.0


# ============================================================
# VALIDATION
# ============================================================


def validate_columns(df, required, name):
    missing = [column for column in required if column not in df.columns]

    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}")


# ============================================================
# RADAR NORMALIZATION
# ============================================================


def normalize_mean_reference(values, higher_is_better=True):
    """
    Convert raw metric values into a relative 0-100 radar index.

    50 = reference mean.

    For higher-is-better metrics:
        higher raw value -> higher radar score

    For lower-is-better metrics:
        lower raw value -> higher radar score

    The result is an index for visualization, NOT a percentage.
    """

    values = pd.Series(values, dtype=float)

    mean = values.mean()
    std = values.std(ddof=0)

    if pd.isna(std) or std == 0:
        return pd.Series(
            np.full(len(values), BASE_SCORE),
            index=values.index,
        )

    if higher_is_better:
        scores = BASE_SCORE + SCALE * (values - mean) / std
    else:
        scores = BASE_SCORE + SCALE * (mean - values) / std

    return scores.clip(0, 100)


# ============================================================
# PACE MODEL
# ============================================================


def fit_pace_model(laps):
    """
    Fit the project's Ridge pace-loss model.

    Target:
        Delta = lap time - driver/race best lap time

    Features are generated by ridge_design() from
    train_pace_loss.py.

    Important:
        ridge_design() requires the list of compounds used
        when fitting the model.
    """

    model = make_ridge()

    # Use the same compound set for both training and prediction.
    compounds = sorted(
        laps["Compound"].dropna().astype(str).str.upper().unique().tolist()
    )

    if not compounds:
        raise ValueError("No valid tyre compounds found in laps data.")

    X = ridge_design(
        laps,
        compounds,
    )

    y = laps["Delta"]

    model.fit(X, y)

    return model, compounds


# ============================================================
# PREDICTION HELPER
# ============================================================


def predict_at_age(
    model,
    compounds,
    compound,
    tyre_age,
    fuel_pct,
    track_temp,
):
    """
    Predict pace loss for one compound at a specified tyre age.
    """

    sample = pd.DataFrame(
        {
            "Compound": [compound],
            "TyreLife": [float(tyre_age)],
            "FuelPct": [float(fuel_pct)],
            "TrackTemp": [float(track_temp)],
        }
    )

    X = ridge_design(
        sample,
        compounds,
    )

    return float(model.predict(X)[0])


# ============================================================
# PACE
# ============================================================


def calculate_pace(
    laps,
    model,
    compounds,
):
    """
    Predicted pace loss at tyre age 5.

    A common median fuel percentage and track temperature
    are used for every compound so the comparison is made
    under the same reference conditions.
    """

    median_fuel = float(laps["FuelPct"].median())

    median_track_temp = float(laps["TrackTemp"].median())

    rows = []

    for compound in COMPOUNDS:
        prediction = predict_at_age(
            model=model,
            compounds=compounds,
            compound=compound,
            tyre_age=5.0,
            fuel_pct=median_fuel,
            track_temp=median_track_temp,
        )

        rows.append(
            {
                "Compound": compound,
                "Predicted Pace Loss (s)": prediction,
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# FRESHNESS
# ============================================================


def calculate_freshness(
    laps,
    model,
    compounds,
):
    """
    Predicted pace loss at tyre age 1.

    Lower predicted loss means a better fresh-tyre
    reference value.
    """

    median_fuel = float(laps["FuelPct"].median())

    median_track_temp = float(laps["TrackTemp"].median())

    rows = []

    for compound in COMPOUNDS:
        prediction = predict_at_age(
            model=model,
            compounds=compounds,
            compound=compound,
            tyre_age=1.0,
            fuel_pct=median_fuel,
            track_temp=median_track_temp,
        )

        rows.append(
            {
                "Compound": compound,
                "Predicted Freshness Loss (s)": prediction,
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# CONSISTENCY
# ============================================================


def calculate_consistency(laps):
    """
    Consistency proxy:

        Standard deviation of Delta

    Lower SD means less variation in pace loss.
    """

    rows = []

    for compound in COMPOUNDS:
        subset = laps[laps["Compound"].str.upper() == compound]

        if subset.empty:
            value = np.nan
        else:
            value = float(subset["Delta"].std())

        rows.append(
            {
                "Compound": compound,
                "Consistency SD (s)": value,
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# DEGRADATION
# ============================================================


def calculate_degradation(
    laps,
    model,
    compounds,
):
    """
    Calculate the fitted pace-loss gradient over the
    observed tyre-age range for each compound.

    Positive gradient:
        predicted pace loss increases with tyre age.

    Negative gradient:
        fitted model predicts decreasing pace loss.

    A negative Intermediate value is treated as a modelling
    warning rather than evidence of superior tyre behaviour.
    """

    median_fuel = float(laps["FuelPct"].median())

    median_track_temp = float(laps["TrackTemp"].median())

    rows = []

    for compound in COMPOUNDS:
        subset = laps[laps["Compound"].str.upper() == compound]

        if subset.empty:
            rows.append(
                {
                    "Compound": compound,
                    "Degradation Rate (s/lap)": np.nan,
                }
            )
            continue

        ages = pd.to_numeric(
            subset["TyreLife"],
            errors="coerce",
        ).dropna()

        if len(ages) < 2:
            rows.append(
                {
                    "Compound": compound,
                    "Degradation Rate (s/lap)": np.nan,
                }
            )
            continue

        low_age = float(ages.quantile(0.02))

        high_age = float(ages.quantile(0.98))

        if high_age <= low_age:
            rows.append(
                {
                    "Compound": compound,
                    "Degradation Rate (s/lap)": np.nan,
                }
            )
            continue

        low_prediction = predict_at_age(
            model=model,
            compounds=compounds,
            compound=compound,
            tyre_age=low_age,
            fuel_pct=median_fuel,
            track_temp=median_track_temp,
        )

        high_prediction = predict_at_age(
            model=model,
            compounds=compounds,
            compound=compound,
            tyre_age=high_age,
            fuel_pct=median_fuel,
            track_temp=median_track_temp,
        )

        gradient = (high_prediction - low_prediction) / (high_age - low_age)

        rows.append(
            {
                "Compound": compound,
                "Degradation Rate (s/lap)": float(gradient),
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# LONGEVITY
# ============================================================


def calculate_longevity(stints):
    """
    Median observed stint length for each compound.

    This is a stint-survival statistic, not a direct physical
    tyre-degradation limit.
    """

    rows = []

    for compound in COMPOUNDS:
        subset = stints[stints["Compound"].str.upper() == compound]

        if subset.empty:
            value = np.nan
        else:
            value = float(subset["stint_length"].median())

        rows.append(
            {
                "Compound": compound,
                "Median Stint Life (laps)": value,
            }
        )

    return pd.DataFrame(rows)


# ============================================================
# MAIN
# ============================================================


def main():

    print("=" * 70)
    print("TYRE RADAR GENERATION")
    print("=" * 70)

    # ========================================================
    # LOAD LAPS
    # ========================================================

    if not LAPS_FILE.exists():
        raise FileNotFoundError(f"Missing input file: {LAPS_FILE}")

    laps = pd.read_csv(LAPS_FILE)

    validate_columns(
        laps,
        [
            "Compound",
            "TyreLife",
            "LapTimeSeconds",
            "Year",
            "Event",
            "Driver",
            "LapNumber",
            "TrackTemp",
        ],
        "laps_clean.csv",
    )

    # ========================================================
    # RECREATE MODEL FEATURES
    # ========================================================

    print("\nPreparing modelling features...")

    # Delta and FuelPct are created here.
    # They are not expected to already exist in laps_clean.csv.
    laps = add_features(laps)

    validate_columns(
        laps,
        [
            "Compound",
            "TyreLife",
            "Delta",
            "FuelPct",
            "TrackTemp",
        ],
        "prepared laps",
    )

    # ========================================================
    # CLEAN LAPS
    # ========================================================

    laps["Compound"] = laps["Compound"].astype(str).str.upper().str.strip()

    laps["TyreLife"] = pd.to_numeric(
        laps["TyreLife"],
        errors="coerce",
    )

    laps["Delta"] = pd.to_numeric(
        laps["Delta"],
        errors="coerce",
    )

    laps["FuelPct"] = pd.to_numeric(
        laps["FuelPct"],
        errors="coerce",
    )

    laps["TrackTemp"] = pd.to_numeric(
        laps["TrackTemp"],
        errors="coerce",
    )

    laps = laps.dropna(
        subset=[
            "Compound",
            "TyreLife",
            "Delta",
            "FuelPct",
            "TrackTemp",
        ]
    ).copy()

    # Keep only the four compounds used by the radar.
    laps = laps[laps["Compound"].isin(COMPOUNDS)].copy()

    if laps.empty:
        raise ValueError("No usable tyre-compound data remains after cleaning.")

    print(f"Usable laps: {len(laps):,}")

    print("\nCompound lap counts:")

    print(
        laps["Compound"]
        .value_counts()
        .reindex(COMPOUNDS)
        .fillna(0)
        .astype(int)
        .to_string()
    )

    # ========================================================
    # LOAD STINTS
    # ========================================================

    if not STINTS_FILE.exists():
        raise FileNotFoundError(f"Missing input file: {STINTS_FILE}")

    stints = pd.read_csv(STINTS_FILE)

    validate_columns(
        stints,
        [
            "Compound",
            "stint_length",
        ],
        "stints.csv",
    )

    stints["Compound"] = stints["Compound"].astype(str).str.upper().str.strip()

    stints["stint_length"] = pd.to_numeric(
        stints["stint_length"],
        errors="coerce",
    )

    stints = stints.dropna(
        subset=[
            "Compound",
            "stint_length",
        ]
    ).copy()

    stints = stints[stints["Compound"].isin(COMPOUNDS)].copy()

    if stints.empty:
        raise ValueError("No usable stint data remains after cleaning.")

    # ========================================================
    # FIT MODEL ONCE
    # ========================================================

    print("\nFitting Ridge pace model...")

    model, model_compounds = fit_pace_model(laps)

    print("Model compounds:", ", ".join(model_compounds))

    # ========================================================
    # CALCULATE METRICS
    # ========================================================

    print("\nCalculating pace...")

    pace = calculate_pace(
        laps,
        model,
        model_compounds,
    )

    print("Calculating longevity...")

    longevity = calculate_longevity(stints)

    print("Calculating consistency...")

    consistency = calculate_consistency(laps)

    print("Calculating degradation...")

    degradation = calculate_degradation(
        laps,
        model,
        model_compounds,
    )

    print("Calculating freshness...")

    freshness = calculate_freshness(
        laps,
        model,
        model_compounds,
    )

    # ========================================================
    # MERGE RAW METRICS
    # ========================================================

    raw = pace.merge(
        longevity,
        on="Compound",
        how="outer",
    )

    raw = raw.merge(
        consistency,
        on="Compound",
        how="outer",
    )

    raw = raw.merge(
        degradation,
        on="Compound",
        how="outer",
    )

    raw = raw.merge(
        freshness,
        on="Compound",
        how="outer",
    )

    raw = raw.set_index("Compound").reindex(COMPOUNDS).reset_index()

    # ========================================================
    # RADAR SCORES
    # ========================================================

    radar = pd.DataFrame(
        {
            "Compound": COMPOUNDS,
            # Lower predicted pace loss is better.
            "Pace": normalize_mean_reference(
                raw["Predicted Pace Loss (s)"],
                higher_is_better=False,
            ),
            # Higher observed stint life is better.
            "Longevity": normalize_mean_reference(
                raw["Median Stint Life (laps)"],
                higher_is_better=True,
            ),
            # Lower variation is better.
            "Consistency": normalize_mean_reference(
                raw["Consistency SD (s)"],
                higher_is_better=False,
            ),
            # Lower degradation rate is better.
            "Degradation Resistance": normalize_mean_reference(
                raw["Degradation Rate (s/lap)"],
                higher_is_better=False,
            ),
            # Lower predicted loss at age 1 is better.
            "Freshness": normalize_mean_reference(
                raw["Predicted Freshness Loss (s)"],
                higher_is_better=False,
            ),
        }
    )

    # ========================================================
    # SAVE CSV FILES
    # ========================================================

    raw.to_csv(
        RAW_OUTPUT,
        index=False,
    )

    radar.to_csv(
        RADAR_OUTPUT,
        index=False,
    )

    # ========================================================
    # PRINT RAW RESULTS
    # ========================================================

    print("\n" + "=" * 70)

    print("RAW METRICS")

    print("=" * 70)

    print(
        raw.to_string(
            index=False,
            float_format=lambda x: f"{x:.4f}",
        )
    )

    # ========================================================
    # PRINT RADAR RESULTS
    # ========================================================

    print("\n" + "=" * 70)

    print("RADAR SCORES")

    print("=" * 70)

    print(
        radar.to_string(
            index=False,
            float_format=lambda x: f"{x:.2f}",
        )
    )

    # ========================================================
    # INTERMEDIATE WARNING
    # ========================================================

    intermediate = raw[raw["Compound"] == "INTERMEDIATE"]

    if not intermediate.empty:
        intermediate_gradient = intermediate["Degradation Rate (s/lap)"].iloc[0]

        if pd.notna(intermediate_gradient) and intermediate_gradient < 0:
            print("\n" + "!" * 70)

            print("WARNING: INTERMEDIATE DEGRADATION")

            print("!" * 70)

            print("The fitted Intermediate degradation gradient is negative.")

            print(
                "Its Degradation Resistance radar score should "
                "therefore be treated as exploratory."
            )

            print(
                "It should NOT be interpreted as proof that "
                "Intermediate tyres resist degradation better."
            )

            print("!" * 70)

    # ========================================================
    # CREATE RADAR CHART
    # ========================================================

    categories = [
        "Pace",
        "Longevity",
        "Consistency",
        "Degradation Resistance",
        "Freshness",
    ]

    angles = np.linspace(
        0,
        2 * np.pi,
        len(categories),
        endpoint=False,
    )

    angles = np.concatenate(
        [
            angles,
            [angles[0]],
        ]
    )

    fig = plt.figure(figsize=(9, 9))

    ax = fig.add_subplot(
        111,
        polar=True,
    )

    for _, row in radar.iterrows():
        values = [float(row[category]) for category in categories]

        values.append(values[0])

        ax.plot(
            angles,
            values,
            linewidth=2,
            label=row["Compound"],
        )

        ax.fill(
            angles,
            values,
            alpha=0.08,
        )

    ax.set_xticks(angles[:-1])

    ax.set_xticklabels(
        categories,
        fontsize=10,
    )

    ax.set_ylim(
        0,
        100,
    )

    ax.set_yticks(
        [
            20,
            40,
            60,
            80,
            100,
        ]
    )

    ax.set_title(
        "F1 Tyre Compound Relative Performance Index",
        pad=25,
        fontsize=14,
        fontweight="bold",
    )

    ax.legend(
        loc="upper right",
        bbox_to_anchor=(1.25, 1.10),
    )

    fig.tight_layout()

    fig.savefig(
        RADAR_PNG,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close(fig)

    # ========================================================
    # FINAL STATUS
    # ========================================================

    print("\n" + "=" * 70)

    print("RADAR GENERATION COMPLETED")

    print("=" * 70)

    print("\nFiles created:")

    print(f"  {RAW_OUTPUT}")

    print(f"  {RADAR_OUTPUT}")

    print(f"  {RADAR_PNG}")

    print("\nRadar interpretation:")

    print("  50 = reference mean")

    print("  Higher score = better for that metric")

    print("  Scores are relative indices, NOT percentages")


if __name__ == "__main__":
    main()
